// tslint:disable
/**
 * 灵镜追踪
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OnEvent
 */
export interface OnEvent {
    /**
     * Semantic64，按钮 uuid
     * @type {string}
     * @memberof OnEvent
     */
    event_id?: string;
    /**
     * 玩家 uuid, 优先使用
     * @type {string}
     * @memberof OnEvent
     */
    player_id?: string;
    /**
     * 未注册用户(外部用户名), 给与随机 player_id
     * @type {string}
     * @memberof OnEvent
     */
    player_anonymous?: string;
    /**
     * Semantic64，渠道 uuid, 可匿名上报
     * @type {string}
     * @memberof OnEvent
     */
    channel_id?: string;
    /**
     * Semantic64，版本 uuid, 可匿名上报  如果 server_id 非空, 则查询 server 关联的版本
     * @type {string}
     * @memberof OnEvent
     */
    version_id?: {
        type: "auto",
        name: "v0.0.1"
    };
    /**
     * 用户设备信息
     * @type {string}
     * @memberof OnEvent
     */
    user_agent?: string;
    /**
     * 按钮触发时间  - null 表示使用服务器时间
     * @type {string}
     * @memberof OnEvent
     */
    time?: string;
    /**
     *
     * @type {string}
     * @memberof OnEvent
     */
    custom?: string;
}


